version: '3.3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: key-cloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
volumes:
  keycloak_data: